theme: jekyll-theme-minimal
title: CEP Aberto SDK (.NET)
description: ğŸ‡§ğŸ‡· ğŸ“ CEPAberto API client wrapper for .NET projects
logo: https://raw.githubusercontent.com/guibranco/CEPAberto/main/logo.png
show_downloads: true
